name: mmvt
channels:
- conda-forge
- open3d-admin
dependencies:
- python>=3.8
- pip
- numpy
- scipy
- matplotlib
- pandas
- scikit-learn
- h5py
- pillow
- statsmodels
- joblib
- numexpr
- tqdm
- nibabel
- mne
- pysftp
- addict
