name: mmvt
channels:
- conda-forge
- open3d-admin
dependencies:
- python>=3.8
- pip
- numpy
- scipy
- matplotlib
- numba
- pandas
- scikit-learn
- h5py
- pillow
- statsmodels
- jupyter
- joblib
- psutil
- numexpr
- traits
- pyface
- traitsui
- imageio
- tqdm
- spyder-kernels
- imageio-ffmpeg>=0.4.1
- dipy
- nibabel
- nilearn
- python-picard
- pyqt
- mne
- mffpy>=0.5.7
- python-graphviz
- pysftp
- moviepy
- flask
- flask
- nitime
- numpy-stl
- open3d
- addict
- plyfile